version: '3'

services:
  web:
    build: .
    ports:
      - "8888:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4444
      MYSQL_DATABASE: team_data
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
